// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfIwgrtvQziRo1FxI8rzS98aZsZFeVHjI',
    appId: '1:900668870343:web:11051ecf69e34fb1d778e2',
    messagingSenderId: '900668870343',
    projectId: 'myroomie-a344d',
    authDomain: 'myroomie-a344d.firebaseapp.com',
    storageBucket: 'myroomie-a344d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCpaQA72fDFhz7BoaqmWsfBzX5ct4pQMA',
    appId: '1:900668870343:android:e8b9d11eb1a693e7d778e2',
    messagingSenderId: '900668870343',
    projectId: 'myroomie-a344d',
    storageBucket: 'myroomie-a344d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Q4dzUaVbBgzQ8mtaR0AsUth5sNN7a9A',
    appId: '1:900668870343:ios:f0dde69b9cd0edbfd778e2',
    messagingSenderId: '900668870343',
    projectId: 'myroomie-a344d',
    storageBucket: 'myroomie-a344d.firebasestorage.app',
    iosBundleId: 'com.example.myroomie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Q4dzUaVbBgzQ8mtaR0AsUth5sNN7a9A',
    appId: '1:900668870343:ios:f0dde69b9cd0edbfd778e2',
    messagingSenderId: '900668870343',
    projectId: 'myroomie-a344d',
    storageBucket: 'myroomie-a344d.firebasestorage.app',
    iosBundleId: 'com.example.myroomie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfIwgrtvQziRo1FxI8rzS98aZsZFeVHjI',
    appId: '1:900668870343:web:ffa072569e5accecd778e2',
    messagingSenderId: '900668870343',
    projectId: 'myroomie-a344d',
    authDomain: 'myroomie-a344d.firebaseapp.com',
    storageBucket: 'myroomie-a344d.firebasestorage.app',
  );
}
